# Configuration file for the Starship prompt
# See: https://starship.rs/config/

# Don't print a new line at the start of the prompt
#add_newline = false

# Configure battery symbols
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

format = "$all"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"


[git_commit]
commit_hash_length = 7
disabled = false
only_detached = false
tag_disabled = false

[java]
disabled = true

prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_commit",
    "git_state",
    "git_status",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character"
]
